const modules=[
{n:"01",title:"Automation Thinking",level:"FOUNDATION",desc:"Learn to see business processes as systems before choosing a tool.",learn:["Spot repetitive work, delays and handoff problems","Define triggers, inputs, decisions, actions and outcomes","Separate deterministic steps from judgment","Map a process before opening any builder"],resources:[["n8n Automation Concepts","https://docs.n8n.io/"],["Zapier Automation Guide","https://zapier.com/learn/"]],assignment:"Choose one repetitive business process and map it on paper. Identify the trigger, data, decisions, actions, exceptions and final business outcome.",hint:"Problem → Trigger → Data → Decision → Action → Outcome → Exception",ready:"You can look at a business problem and describe the system it needs without naming a specific tool."},
{n:"02",title:"Workflow Automation",level:"BEGINNER",desc:"Build predictable processes with visual automation tools or code.",learn:["When a deterministic workflow is the right solution","Nodes/steps, data mapping and branching","IF/Switch logic and transformations","How n8n, Make, Zapier and code differ","Debugging workflow executions"],resources:[["n8n Docs","https://docs.n8n.io/"],["Make Academy","https://academy.make.com/"],["Zapier Learn","https://zapier.com/learn/"]],assignment:"Build the same simple lead-capture process in one workflow platform of your choice. Capture, clean, store and respond.",hint:"Trigger → Normalize → Rules → Store → Action",ready:"You can build and debug a multi-step workflow in at least one platform and explain how you would reproduce it elsewhere."},
{n:"03",title:"APIs, Webhooks & Integrations",level:"BEGINNER+",desc:"Learn the language that lets different tools talk to each other.",learn:["APIs, endpoints and request/response","GET, POST, headers, parameters and authentication","JSON and status codes","Webhooks and event-driven systems","Reading documentation instead of searching for an exact tutorial"],resources:[["Postman Learning","https://learning.postman.com/"],["MDN HTTP Overview","https://developer.mozilla.org/en-US/docs/Web/HTTP/Overview"],["n8n HTTP Request","https://docs.n8n.io/integrations/builtin/core-nodes/n8n-nodes-base.httprequest/"]],assignment:"Connect to an API you have never used before. Send a request, inspect the response, extract useful data and pass it into another app.",hint:"App/Event → HTTP/API → JSON Response → Transform → Destination",ready:"You can read basic API documentation and connect a new service without needing an exact step-by-step video."},
{n:"04",title:"Working With LLMs",level:"INTERMEDIATE",desc:"Use language models as reasoning components inside larger systems.",learn:["What LLMs are good and bad at","Prompt design for business tasks","Structured outputs and schemas","Classification, extraction and summarization","Tool calling and validating model output","Choosing models based on the task, not hype"],resources:[["OpenAI Developers","https://developers.openai.com/"],["Anthropic Docs","https://docs.anthropic.com/"],["Google AI for Developers","https://ai.google.dev/"]],assignment:"Use any major LLM to classify a real enquiry and return strict structured data. Validate the output before your workflow takes action.",hint:"Input → Model → Structured Output → Validate → Business Logic",ready:"You can use an LLM inside a system without letting unpredictable model output control everything."},
{n:"05",title:"AI Agents",level:"INTERMEDIATE",desc:"Understand goal-driven systems that can reason, use tools and choose actions.",learn:["Agent vs automation vs chatbot","Goals, instructions and boundaries","Tools and permissions","Memory and context","Human approval and autonomy levels","When an agent is unnecessary"],resources:[["OpenAI Agents","https://developers.openai.com/learn/agents"],["Anthropic: Building Effective Agents","https://www.anthropic.com/research/building-effective-agents"],["n8n Advanced AI","https://docs.n8n.io/advanced-ai/"]],assignment:"Build an agent in a platform of your choice that can understand a request and use at least two tools to work toward a goal.",hint:"Goal → Agent → Context/Memory ↔ Tools → Decision → Action → Human if needed",ready:"You can justify when to use an agent, choose its tools and define where human control belongs."},
{n:"06",title:"Modern Agent Platforms",level:"EXPLORE",desc:"Explore agent products without becoming dependent on any one of them.",learn:["Computer-using and browser-using agents","Persistent agents and routines","Coding agents and software-building agents","Where agent platforms replace manual orchestration","Where deterministic workflows remain safer","How to evaluate a new agent product quickly"],resources:[["Grok Bot Docs","https://docs.x.ai/grok-bot/overview"],["OpenAI Developers","https://developers.openai.com/"],["Anthropic Claude Code","https://docs.anthropic.com/en/docs/claude-code/overview"]],assignment:"Choose one modern agent platform. Give it a real multi-step task, observe where it succeeds or fails and write down what you would automate deterministically instead.",hint:"Task → Agent capabilities → Permissions → Actions → Observe → Decide what needs a workflow",ready:"A new AI agent can launch tomorrow and you know how to evaluate it rather than starting your learning from zero."},
{n:"07",title:"Knowledge, Memory & RAG",level:"INTERMEDIATE",desc:"Give AI systems useful business context instead of relying on model memory.",learn:["Context vs persistent memory vs knowledge","Retrieval and RAG","Documents, chunking and embeddings conceptually","Vector stores and search","Grounding answers in source material","When simple search is enough"],resources:[["n8n RAG","https://docs.n8n.io/advanced-ai/rag-in-n8n/"],["Supabase AI & Vectors","https://supabase.com/docs/guides/ai"]],assignment:"Create a knowledge assistant using real documents. Test it with questions the base model could not reliably answer.",hint:"Knowledge → Index → Retrieve relevant context → Model/Agent → Grounded answer",ready:"You can choose how an AI system should access business knowledge and test whether retrieval actually improves answers."},
{n:"08",title:"Business System Architecture",level:"INTERMEDIATE+",desc:"Combine workflows, agents, models and business tools into one coherent system.",learn:["Start from the business outcome","Choose agent vs workflow vs hybrid architecture","CRM, messaging, email and database integrations","System boundaries and handoffs","Human-in-the-loop design","Cost and complexity trade-offs"],resources:[["n8n Integrations","https://n8n.io/integrations/"],["Make Integrations","https://www.make.com/en/integrations"],["Zapier Apps","https://zapier.com/apps"]],assignment:"Design a lead-management system without committing to a platform first. Then choose the tools that best fit each part.",hint:"Channel → Understand → Decide → Execute → Store → Notify → Measure",ready:"Given a business problem, you can defend why each component is an agent, workflow, model, database or human step."},
{n:"09",title:"Deployment, Security & Reliability",level:"PRODUCTION",desc:"Make systems safe, observable and dependable after the demo works.",learn:["Cloud vs local development","Hosting and deployment options","Credentials, secrets and permissions","Retries, errors, logging and alerts","Duplicate prevention and idempotency","Backups, cost controls and human approval"],resources:[["n8n Hosting","https://docs.n8n.io/hosting/"],["OWASP Secrets Management","https://cheatsheetseries.owasp.org/cheatsheets/Secrets_Management_Cheat_Sheet.html"],["Vercel Docs","https://vercel.com/docs"]],assignment:"Take a system you built earlier and make it production-aware: secure credentials, add error handling, logs, duplicate protection and an escalation path.",hint:"System → Guardrails → Execute → Log → Failure path → Retry/Escalate → Monitor",ready:"You can explain what happens when the system fails, who owns it and how credentials and sensitive actions are protected."},
{n:"10",title:"Portfolio & Client Readiness",level:"READY TO SOLVE",desc:"Prove you can solve business problems, not just operate software.",learn:["Present the pain before the technology","Architecture diagrams and documentation","Short demos and handover guides","Case studies focused on outcomes","Scoping and explaining trade-offs","Showing adaptability across tools"],resources:[["GitHub Docs","https://docs.github.com/"],["Loom","https://www.loom.com/"]],assignment:"Publish three systems that use different approaches: one deterministic workflow, one agent and one hybrid system. Explain why you chose each architecture.",hint:"Problem → Constraints → Architecture choice → Build → Demo → Outcome → Lessons",ready:"You can receive a business problem, design an appropriate system and explain your choices without defaulting to one platform."}
]
const progressKey="automateWithAIProgressV1";\nlet progress=JSON.parse(localStorage.getItem(progressKey)||"{\\\"modules\\\":[],\\\"projects\\\":[]}") ;\nconst grid=document.querySelector("#roadmapGrid");
grid.innerHTML=modules.map((m,i)=>`<article class="stage module-card ${progress.modules.includes(i)?"is-complete":""}" data-module="${i}" tabindex="0"><div class="stage-top"><span class="num">${m.n}</span><span class="tag">${m.level}</span></div><h3>${m.title}</h3><p>${m.desc}</p><div class="challenge"><b>YOUR CHALLENGE</b><br>${m.assignment}</div><div class="open-module"><span class="module-status">${progress.modules.includes(i)?"✓ Completed":"Open mini module"}</span><span>→</span></div></article>`).join("");
const modal=document.createElement("div");modal.className="module-modal";modal.innerHTML='<div class="modal-backdrop"></div><div class="module-panel" role="dialog" aria-modal="true"><button class="close-module" aria-label="Close">×</button><div id="moduleContent"></div></div>';document.body.appendChild(modal);
function openModule(i){const m=modules[i];document.querySelector("#moduleContent").innerHTML=`<div class="module-head"><span class="num">STAGE ${m.n}</span><span class="tag">${m.level}</span><h2>${m.title}</h2><p>${m.desc}</p></div><div class="module-block"><span class="kicker">WHAT YOU'LL LEARN</span><ul>${m.learn.map(x=>`<li>${x}</li>`).join("")}</ul></div><div class="module-block"><span class="kicker">BEST FREE RESOURCES</span><div class="module-resources">${m.resources.map(r=>`<a href="${r[1]}" target="_blank" rel="noopener"><b>${r[0]}</b><span>Open resource ↗</span></a>`).join("")}</div></div><div class="module-block assignment"><span class="kicker">YOUR PRACTICAL ASSIGNMENT</span><h3>${m.assignment}</h3></div><details class="hint"><summary>Stuck? Reveal the architecture hint</summary><p>${m.hint}</p></details><div class="module-block completion"><span class="kicker">YOU'RE READY TO MOVE ON WHEN</span><p>${m.ready}</p></div><button class="complete-btn ${progress.modules.includes(i)?"done":""}" data-complete="${i}">${progress.modules.includes(i)?"✓ Stage completed":"Mark stage complete"}</button><div class="module-next">${i<modules.length-1?`Next: Stage ${modules[i+1].n} • ${modules[i+1].title}`:"You made it through the roadmap. Now build your portfolio."}</div>`;modal.classList.add("active");document.body.classList.add("modal-open");}
function closeModule(){modal.classList.remove("active");document.body.classList.remove("modal-open")}
grid.addEventListener("click",e=>{const c=e.target.closest(".module-card");if(c)openModule(+c.dataset.module)});grid.addEventListener("keydown",e=>{const c=e.target.closest(".module-card");if(c&&(e.key==="Enter"||e.key===" ")){e.preventDefault();openModule(+c.dataset.module)}});modal.querySelector(".close-module").onclick=closeModule;modal.addEventListener("click",e=>{const b=e.target.closest("[data-complete]");if(!b)return;const i=+b.dataset.complete;if(progress.modules.includes(i))progress.modules=progress.modules.filter(x=>x!==i);else progress.modules.push(i);saveProgress();openModule(i);renderProgress();});modal.querySelector(".modal-backdrop").onclick=closeModule;document.addEventListener("keydown",e=>{if(e.key==="Escape")closeModule()});
const projects=[["BEGINNER","Lead Capture System","A new enquiry arrives. Capture it, clean the data, save it and send a confirmation without manual work."],["BEGINNER+","Smart Lead Router","Qualify an enquiry using rules, route it correctly and trigger the right follow-up."],["INTERMEDIATE","AI Lead Qualification","Use AI to understand an enquiry, return structured data, update a CRM and generate a contextual response."],["INTERMEDIATE","WhatsApp AI Agent","Give an agent memory and tools so it can answer questions, retrieve information and update customer records."],["INTERMEDIATE+","Training Company System","Automate registrations, confirmations, participant records, certificates and follow-ups."],["ADVANCED","Production Business Agent","Combine tools, memory, knowledge, approvals, logging, retries and deployment into one reliable system."]];
document.querySelector("#projectGrid").innerHTML=projects.map((p,i)=>`<article class="project ${progress.projects.includes(i)?"project-complete":""}" data-project="${i}"><small>${p[0]}</small><h3>${p[1]}</h3><p>${p[2]}</p><button class="project-check" data-project-check="${i}">${progress.projects.includes(i)?"✓ Built":"Mark as built"}</button></article>`).join("");\ndocument.querySelector("#projectGrid").addEventListener("click",e=>{const b=e.target.closest("[data-project-check]");if(!b)return;const i=+b.dataset.projectCheck;if(progress.projects.includes(i))progress.projects=progress.projects.filter(x=>x!==i);else progress.projects.push(i);saveProgress();location.reload();});
const resources=[["n8n Learning","Official n8n documentation, courses and workflow concepts.","https://docs.n8n.io/"],["n8n Templates","Reverse-engineer real workflows instead of only watching videos.","https://n8n.io/workflows/"],["OpenAI Agents","Learn tools, orchestration and agent-building concepts.","https://developers.openai.com/learn/agents"],["Anthropic","Practical material on effective agent design and when simpler workflows are better.","https://www.anthropic.com/research/building-effective-agents"],["Postman Learning","Learn APIs, requests, authentication and testing by doing.","https://learning.postman.com/"],["LangChain Academy","Go deeper into agent engineering after you understand the fundamentals.","https://academy.langchain.com/"]];
document.querySelector("#resourceGrid").innerHTML=resources.map(r=>`<article class="resource"><span class="kicker">FREE RESOURCE</span><h3>${r[0]}</h3><p>${r[1]}</p><a href="${r[2]}" target="_blank" rel="noopener">Open resource ↗</a></article>`).join("");
function saveProgress(){localStorage.setItem(progressKey,JSON.stringify(progress));renderCards();}
function renderCards(){document.querySelectorAll(".module-card").forEach((c,i)=>{const done=progress.modules.includes(i);c.classList.toggle("is-complete",done);const s=c.querySelector(".module-status");if(s)s.textContent=done?"✓ Completed":"Open mini module"});}
function renderProgress(){const done=progress.modules.length;const pct=Math.round(done/modules.length*100);const built=progress.projects.length;const bar=document.querySelector("#progressBarFill");if(bar)bar.style.width=pct+"%";const count=document.querySelector("#progressCount");if(count)count.textContent=done+"/10 stages completed";const percent=document.querySelector("#progressPercent");if(percent)percent.textContent=pct+"%";const projectsCount=document.querySelector("#projectsCount");if(projectsCount)projectsCount.textContent=built+"/6 projects built";}
renderProgress();
const toolbox=[
["WORKFLOW AUTOMATION","n8n • Make • Zapier • Code","Predictable multi-step processes, integrations and business rules."],
["AGENT PLATFORMS","Grok Bot • OpenAI agent experiences • emerging agent platforms","Goal-driven work, browser/computer use, tools, context and flexible multi-step tasks."],
["CODING AGENTS","Codex • Claude Code • Cursor-style tools","Understand, create, debug and modify software with AI assistance."],
["MODELS","OpenAI • Claude • Gemini • Grok • Qwen","Reasoning, extraction, classification, generation and tool calling. Choose by task."],
["DATA & KNOWLEDGE","Supabase • SQL • Vector stores • Drive","Store business state, customer data and knowledge that AI systems need."],
["COMMUNICATION","WhatsApp • Email • Telegram • Slack","Where customers and teams interact with your systems."],
["INFRASTRUCTURE","Cloud platforms • Vercel • Railway • VPS","Keep systems online, secure and available beyond your laptop."],
["HUMANS","Approvals • Exceptions • Escalations","Not everything should be autonomous. Good systems know when to involve a person."]
];
document.querySelector("#toolboxGrid").innerHTML=toolbox.map(t=>`<article class="tool-card"><span class="kicker">${t[0]}</span><h3>${t[1]}</h3><p>${t[2]}</p></article>`).join("");